general:
steps:
  mtaBuild:
    buildTarget: 'CF'
  cloudFoundryDeploy:
    deployTool: 'mtaDeployPlugin'
    deployType: 'standard'
    cloudFoundry:
      org: 'e49a3acdtrial_e49a3acdtrial'
      space: 'dev'
      credentialsId: 'cf-cred'
